language: node_js

# Version 10 is the most recent.
node_js:
  - '10'

# npm version 6 comes with version 10.
before_install: if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi

addons:
    code_climate:
        repo_token: 060d3f549ff61c04e238d60201ae8d770079b182df927a89c18095b9f318efe5

before_script:
  - npm install codeclimate-test-reporter nyc -g

script:
  - npm test

after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info

# Makes sure node_modules exists.
cache:
  directories:
    - node_modules
